Algoritmo "semnome"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/05/2018
Var
 n:real


inicio
   escreva("Informe O Numemero: ")
   leia(n)
   limpatela

   se(n >= 100) e (N <=200)entao
      escreval(" ")
      escreval(n," Esta no Intervalo")
   senao
      escreval(" ")
      escreval(n," Não Esta no Intervalo")
   fimse


Fimalgoritmo