Algoritmo "semnome"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Sidney
// Data atual  : 21/05/2018
Var
s:caracter


Inicio
escreval(" (M) - Masculino / (F) - Feminino ")
escreval("  ")
escreva("Imforme o Sexo: ")
leia(s)

se(s = "M")ou (s = "m")entao
escreval("  ")
escreval(" MASCULINO  ")
senao
escreval("  ")
escreval(" FEMININO ")
fimse

Fimalgoritmo