Algoritmo "semnome"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Sidney
// Data atual  : 21/05/2018
Var
l:caracter


Inicio
   escreva("Imforme a letra: ")
   leia(l)

   se(l = "a")ou(l = "e")ou(l = "i")ou(l = "o")ou(l = "u")entao
      escreval(" ")
      escreval("É Vogal")
   senao
      escreval(" ")
      escreval("Não É Vogal")
   fimse
Fimalgoritmo