Algoritmo "1- Maior ou menor de idade"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Sidney
// Data atual  : 21/05/2018
Var
   idade:inteiro


Inicio
   escreva("Informe Sua Idade: ")
   leia(idade)

   se(Idade >= 18)entao
      escreval("")
      escreval("Você é Maior de Idade")
   senao
      escreval("")
      escreval("Você é Menor de Idade")
   fimse
Fimalgoritmo