Algoritmo "2- Valor Maior"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Sidney
// Data atual  : 21/05/2018
Var
  v1,v2:real


Inicio
   escreva("Informe o Primeiro Valor: ")
   leia(v1)
   escreva("Informe o Segundo Valor: ")
   leia(v2)

   se(v1 > v2)entao
      escreval("")
      escreval(v1," é maior que ",v2)
   senao
      escreval("")
      escreval(v2," é maior que ",v1)
   fimse
Fimalgoritmo