Algoritmo "1- distancia"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/05/2018
Var
x,d:real


Inicio
Escreva("Qual a Distancia X, em Km: ")
leia(x)

d <-  (x /(90 - 60)) * 60

Escreval("Demoraria ",d," minutos")

Fimalgoritmo